package main

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"sync"
	"time"
)

// ---- data model ----

type State struct {
	Interface InterfaceConfig `json:"interface"`
	Peers     []Peer          `json:"peers"`
}

type InterfaceConfig struct {
	Address    string `json:"address"`
	ListenPort int    `json:"listenPort"`
	PrivateKey string `json:"privateKey"`
	DNS        string `json:"dns"`
	MTU        int    `json:"mtu"`
	Table      string `json:"table"`
	PreUp      string `json:"preUp"`
	PostUp     string `json:"postUp"`
	PreDown    string `json:"preDown"`
	PostDown   string `json:"postDown"`
	SaveConfig bool   `json:"saveConfig"`
}

type Peer struct {
	ID                  string `json:"id"`
	Name                string `json:"name"`
	PublicKey           string `json:"publicKey"`
	PrivateKey          string `json:"privateKey,omitempty"`
	PresharedKey        string `json:"presharedKey,omitempty"`
	AllowedIPs          string `json:"allowedIPs"`
	Endpoint            string `json:"endpoint,omitempty"`
	PersistentKeepalive int    `json:"persistentKeepalive"`
	CreatedAt           string `json:"createdAt"`
}

// ---- state file operations ----

func LoadState(path string) (*State, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var s State
	if err := json.Unmarshal(data, &s); err != nil {
		return nil, err
	}
	return &s, nil
}

func (s *State) Save(path string) error {
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0600)
}

// ---- config file generation ----

func (s *State) GenerateConfig() string {
	var b strings.Builder
	b.WriteString("# Generated by WireGuard UI\n\n")
	b.WriteString("[Interface]\n")
	if s.Interface.PrivateKey != "" {
		b.WriteString(fmt.Sprintf("PrivateKey = %s\n", s.Interface.PrivateKey))
	}
	if s.Interface.Address != "" {
		b.WriteString(fmt.Sprintf("Address = %s\n", s.Interface.Address))
	}
	if s.Interface.ListenPort > 0 {
		b.WriteString(fmt.Sprintf("ListenPort = %d\n", s.Interface.ListenPort))
	}
	if s.Interface.DNS != "" {
		b.WriteString(fmt.Sprintf("DNS = %s\n", s.Interface.DNS))
	}
	if s.Interface.MTU > 0 {
		b.WriteString(fmt.Sprintf("MTU = %d\n", s.Interface.MTU))
	}
	if s.Interface.Table != "" {
		b.WriteString(fmt.Sprintf("Table = %s\n", s.Interface.Table))
	}
	if s.Interface.SaveConfig {
		b.WriteString("SaveConfig = true\n")
	}
	if s.Interface.PreUp != "" {
		for _, line := range strings.Split(s.Interface.PreUp, ";") {
			line = strings.TrimSpace(line)
			if line != "" {
				b.WriteString(fmt.Sprintf("PreUp = %s\n", line))
			}
		}
	}
	if s.Interface.PostUp != "" {
		for _, line := range strings.Split(s.Interface.PostUp, ";") {
			line = strings.TrimSpace(line)
			if line != "" {
				b.WriteString(fmt.Sprintf("PostUp = %s\n", line))
			}
		}
	}
	if s.Interface.PreDown != "" {
		for _, line := range strings.Split(s.Interface.PreDown, ";") {
			line = strings.TrimSpace(line)
			if line != "" {
				b.WriteString(fmt.Sprintf("PreDown = %s\n", line))
			}
		}
	}
	if s.Interface.PostDown != "" {
		for _, line := range strings.Split(s.Interface.PostDown, ";") {
			line = strings.TrimSpace(line)
			if line != "" {
				b.WriteString(fmt.Sprintf("PostDown = %s\n", line))
			}
		}
	}
	for _, p := range s.Peers {
		b.WriteString("\n[Peer]\n")
		b.WriteString(fmt.Sprintf("PublicKey = %s\n", p.PublicKey))
		if p.PresharedKey != "" {
			b.WriteString(fmt.Sprintf("PresharedKey = %s\n", p.PresharedKey))
		}
		b.WriteString(fmt.Sprintf("AllowedIPs = %s\n", p.AllowedIPs))
		if p.Endpoint != "" {
			b.WriteString(fmt.Sprintf("Endpoint = %s\n", p.Endpoint))
		}
		if p.PersistentKeepalive > 0 {
			b.WriteString(fmt.Sprintf("PersistentKeepalive = %d\n", p.PersistentKeepalive))
		}
	}
	return b.String()
}

func (s *State) WriteConfig(path string) error {
	return os.WriteFile(path, []byte(s.GenerateConfig()), 0600)
}

// ---- key generation ----

func genPrivateKey() (string, error) {
	out, err := exec.Command("wg", "genkey").Output()
	if err != nil {
		return "", fmt.Errorf("wg genkey: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

func pubkeyFromPrivate(privateKey string) (string, error) {
	cmd := exec.Command("wg", "pubkey")
	cmd.Stdin = strings.NewReader(privateKey)
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("wg pubkey: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

func genPSK() (string, error) {
	out, err := exec.Command("wg", "genpsk").Output()
	if err != nil {
		return "", fmt.Errorf("wg genpsk: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

// ---- wireguard operations ----

type WgPeerStatus struct {
	PublicKey           string `json:"publicKey"`
	PresharedKey        string `json:"presharedKey"`
	Endpoint            string `json:"endpoint"`
	AllowedIPs          string `json:"allowedIPs"`
	LatestHandshake     string `json:"latestHandshake"`
	TransferRx          int64  `json:"transferRx"`
	TransferTx          int64  `json:"transferTx"`
	PersistentKeepalive int    `json:"persistentKeepalive"`
}

type WgStatus struct {
	Interface string         `json:"interface"`
	PublicKey string         `json:"publicKey"`
	ListenPort int           `json:"listenPort"`
	Peers     []WgPeerStatus `json:"peers"`
}

var wgMu sync.Mutex

func wgShowDump(iface string) (*WgStatus, error) {
	wgMu.Lock()
	defer wgMu.Unlock()

	out, err := exec.Command("wg", "show", iface, "dump").Output()
	if err != nil {
		return nil, err
	}
	return parseWgDump(string(out)), nil
}

func parseWgDump(dump string) *WgStatus {
	lines := strings.Split(strings.TrimSpace(dump), "\n")
	if len(lines) == 0 {
		return &WgStatus{Interface: "wg0"}
	}
	status := &WgStatus{}
	for i, line := range lines {
		fields := strings.Split(line, "\t")
		if i == 0 {
			if len(fields) >= 1 {
				status.Interface = fields[0]
			}
			if len(fields) >= 2 {
				status.PublicKey = fields[1]
			}
			if len(fields) >= 3 {
				fmt.Sscanf(fields[2], "%d", &status.ListenPort)
			}
		} else {
			peer := WgPeerStatus{}
			if len(fields) >= 1 {
				peer.PublicKey = fields[0]
			}
			if len(fields) >= 2 {
				peer.PresharedKey = fields[1]
			}
			if len(fields) >= 3 {
				peer.Endpoint = fields[2]
			}
			if len(fields) >= 4 {
				peer.AllowedIPs = fields[3]
			}
			if len(fields) >= 5 {
				peer.LatestHandshake = fields[4]
			}
			if len(fields) >= 6 {
				fmt.Sscanf(fields[5], "%d", &peer.TransferRx)
			}
			if len(fields) >= 7 {
				fmt.Sscanf(fields[6], "%d", &peer.TransferTx)
			}
			if len(fields) >= 8 {
				fmt.Sscanf(fields[7], "%d", &peer.PersistentKeepalive)
			}
			status.Peers = append(status.Peers, peer)
		}
	}
	return status
}

func wgQuickDown(iface string) error {
	wgMu.Lock()
	defer wgMu.Unlock()
	exec.Command("wg-quick", "down", iface).Run()
	exec.Command("ip", "link", "del", iface).Run()
	if isWgUp(iface) {
		return fmt.Errorf("interface %s still up after down", iface)
	}
	return nil
}

func wgQuickUp(iface, confPath string) error {
	wgMu.Lock()
	defer wgMu.Unlock()
	return exec.Command("wg-quick", "up", confPath).Run()
}

func isWgUp(iface string) bool {
	out, err := exec.Command("wg", "show", iface).Output()
	if err != nil {
		return false
	}
	return strings.Contains(string(out), "interface: "+iface)
}

// ---- peer config export ----

func (s *State) PeerClientConfig(peerID string, serverEndpoint string) (string, error) {
	var peer *Peer
	for i := range s.Peers {
		if s.Peers[i].ID == peerID {
			peer = &s.Peers[i]
			break
		}
	}
	if peer == nil {
		return "", fmt.Errorf("peer not found")
	}

	serverPubkey, err := pubkeyFromPrivate(s.Interface.PrivateKey)
	if err != nil {
		serverPubkey = "(could not derive — set interface private key)"
	}

	var b strings.Builder
	b.WriteString("[Interface]\n")
	if peer.PrivateKey != "" {
		b.WriteString(fmt.Sprintf("PrivateKey = %s\n", peer.PrivateKey))
	}
	b.WriteString(fmt.Sprintf("Address = %s\n", peer.AllowedIPs))
	if s.Interface.DNS != "" {
		b.WriteString(fmt.Sprintf("DNS = %s\n", s.Interface.DNS))
	}
	b.WriteString("\n[Peer]\n")
	b.WriteString(fmt.Sprintf("PublicKey = %s\n", serverPubkey))
	if serverEndpoint != "" {
		b.WriteString(fmt.Sprintf("Endpoint = %s\n", serverEndpoint))
	} else if s.Interface.ListenPort > 0 {
		b.WriteString(fmt.Sprintf("Endpoint = SERVER_IP:%d\n", s.Interface.ListenPort))
	}
	b.WriteString("AllowedIPs = 0.0.0.0/0\n")
	if peer.PersistentKeepalive > 0 {
		b.WriteString(fmt.Sprintf("PersistentKeepalive = %d\n", peer.PersistentKeepalive))
	}

	return b.String(), nil
}

// ---- helpers ----

func generateID() string {
	b := make([]byte, 8)
	rand.Read(b)
	return fmt.Sprintf("%x", b)
}

func now() string {
	return time.Now().UTC().Format(time.RFC3339)
}

func sanitizeFilename(name string) string {
	return strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			return r
		}
		return '_'
	}, name)
}

func ParseConfig(raw string) (InterfaceConfig, []Peer, error) {
	var cfg InterfaceConfig
	var peers []Peer
	var cur *Peer
	section := ""

	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = strings.ToLower(strings.TrimSpace(line[1 : len(line)-1]))
			if section == "peer" {
				peers = append(peers, Peer{})
				cur = &peers[len(peers)-1]
			}
			continue
		}
		kv := strings.SplitN(line, "=", 2)
		if len(kv) != 2 {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(kv[0]))
		val := strings.TrimSpace(kv[1])

		switch section {
		case "interface":
			switch key {
			case "privatekey":
				cfg.PrivateKey = val
			case "address":
				cfg.Address = val
			case "listenport":
				p, _ := strconv.Atoi(val)
				cfg.ListenPort = p
			case "dns":
				if cfg.DNS == "" {
					cfg.DNS = val
				} else {
					cfg.DNS += ", " + val
				}
			case "mtu":
				m, _ := strconv.Atoi(val)
				cfg.MTU = m
			case "table":
				cfg.Table = val
			case "preup":
				if cfg.PreUp == "" { cfg.PreUp = val } else { cfg.PreUp += "; " + val }
			case "postup":
				if cfg.PostUp == "" { cfg.PostUp = val } else { cfg.PostUp += "; " + val }
			case "predown":
				if cfg.PreDown == "" { cfg.PreDown = val } else { cfg.PreDown += "; " + val }
			case "postdown":
				if cfg.PostDown == "" { cfg.PostDown = val } else { cfg.PostDown += "; " + val }
			case "saveconfig":
				cfg.SaveConfig = strings.EqualFold(val, "true")
			}
		case "peer":
			if cur == nil {
				continue
			}
			switch key {
			case "publickey":
				cur.PublicKey = val
			case "presharedkey":
				cur.PresharedKey = val
			case "allowedips":
				if cur.AllowedIPs == "" {
					cur.AllowedIPs = val
				} else {
					cur.AllowedIPs += ", " + val
				}
			case "endpoint":
				cur.Endpoint = val
			case "persistentkeepalive":
				k, _ := strconv.Atoi(val)
				cur.PersistentKeepalive = k
			}
		}
	}

	for i := range peers {
		peers[i].ID = generateID()
		peers[i].CreatedAt = now()
		if peers[i].Name == "" {
			peers[i].Name = fmt.Sprintf("peer-%d", i+1)
		}
		if peers[i].PersistentKeepalive == 0 {
			peers[i].PersistentKeepalive = 25
		}
	}

	return cfg, peers, nil
}
